[project]
name = "imagereader"
version = "0.1.0"
description = "This image reader is used for reading medical images and generating reports"
readme = "README.md"
authors = [
    { name = "uzmailyas", email = "uzma.paec@gmail.com" }
]
requires-python = ">=3.11,<3.12"
dependencies = [
    "streamlit>=1.32.0",
    "pyarrow>=12.0.1,<13.0.0",
    "facenet-pytorch",
    "matplotlib",
    "transformers",
    "torch",
    "torchvision",
    "gradio>=4.19.0",
    "rich>=13.9.4",
]

[project.scripts]
imagereader = "imagereader.main:main"
getfile = "imagereader.main:get_file_from_user"
read = "imagereader.main:read"
prac = "imagereader.prac:uz"
streamlit_app = "imagereader.streamlit_app:main"
gradio_app = "imagereader.gradio_app:main"
feature = "imagereader.feature:main"
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
