[project]
name = "imagereader"
version = "0.1.0"
description = "This image reader is used for reading medical images and generating reports"
readme = "README.md"
authors = [
    { name = "uzmailyas", email = "uzma.paec@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
imagereader = "imagereader:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
